name = "Elixir Phoenix"
description = "Phoenix + Elixir project"
skills = ["elixir-architect", "prod-eval", "bit-ship", "phoenix-server","beans","beans-stats", "dokku-helper","db-migrations"]
commands = ["teach"]
mcps = ["tidewave"]

snippets = ["elixir_rules", "beans_usage", "plan"]
